version: "3.8"

services:
  stream-netcheck:
    build: .
    image: stream-netcheck:latest
    container_name: stream-netcheck
    restart: unless-stopped
    ports:
      - "8055:8055"
    environment:
      - TZ=Europe/Warsaw
